version: '3.4'
services:
  virtuoso:
    image: aokinobu/virtuoso:v7.2.4.2
    ports:
      - 1111:1111
      - 8890:8890
    volumes:
      - ${HOME}/${SITE_CODE:-glygen-array}/virtuoso/data:/virtuoso
    restart: always

networks:
  default:
    external:
      name: ${GLYGEN_ARRAY_NETWORK:-glygen-array-network}
