version: '3.4'
services:
  virtuoso:
    build: .
    image: aokinobu/virtuoso:v7.2.4.2
    ports:
      - 1111:1111
      - 8890:8890
    volumes:
      - ${PWD}/config/virtuoso.ini:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.ini
      - ${HOME}/${SITE_CODE:-glygen-array}/virtuoso/data:/usr/local/virtuoso-opensource/var/lib/virtuoso
    restart: always

networks:
  default:
    external:
      name: ${GLYGEN_ARRAY_NETWORK:-glygen-array-network}
