version: '2'
services:
#  https:
  java:
    image: maven:3.3.9-jdk-8
    ports:
      - 81:8080
    volumes:
      - ${HOME}/nmr/maven:/root/.m2
      - ${HOME}/glytoucan/java/upload:/upload
      - /etc/localtime:/etc/localtime
      - ./nmrboot:/workspace
    working_dir: /workspace/
    command: mvn -U -DskipTests=true spring-boot:run $SPRING_PROFILE
    environment:
      - GOOGLE_OAUTH2_CLIENTID
      - GOOGLE_OAUTH2_CLIENTSECRET
      - SPRING_TRIPLESTORE_PASSWORD
      - SPRING_TRIPLESTORE_URL
    links:
      - virtuoso:internal.virtuoso
      - postgres:internal.postgres
    restart: always
  glycanbuilder:
    build: docker-glycanbuilder
#    image: glytoucan_glycanbuilder:v${GTC_VERSION}
    ports:
     - "8080:80"
    volumes:
     - /etc/localtime:/etc/localtime
    restart: always
  postgres:
# docker run --name psql-service -p 5432:5432 -d postgres
    image: postgres
    ports:
      - "5432:5432"
