version: '2'
services:
#  https:
  java:
    image: maven:3.3.9-jdk-8
    ports:
      - 81:8080
    volumes:
      - ${HOME}/nmr/maven:/root/.m2
      - ${HOME}/glytoucan/java/upload:/upload
      - /etc/localtime:/etc/localtime
      - ./nmrboot:/workspace
    working_dir: /workspace/
    command: mvn -U -DskipTests=true spring-boot:run $SPRING_PROFILE
    environment:
      - GOOGLE_OAUTH2_CLIENTID
      - GOOGLE_OAUTH2_CLIENTSECRET
      - SPRING_TRIPLESTORE_PASSWORD
      - SPRING_TRIPLESTORE_URL
    links:
      - virtuoso:internal.virtuoso
      - postgres:internal.postgres
    restart: always
  virtuoso:
    image: aokinobu/virtuoso:v7.2.4.2
    ports:
      - 1111:1111
      - 8890:8890
    volumes:
      - ${HOME}/${SITE_CODE}/virtuoso/data:/virtuoso
      - /etc/localtime:/etc/localtime
    environment:
      - VIRTUAL_HOST=${VIRTUOSO_VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUOSO_VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${VIRTUOSO_VIRTUAL_HOST}
      - LETSENCRYPT_PORT=${VIRTUOSO_VIRTUAL_PORT}
      - LETSENCRYPT_EMAIL=${SITE_EMAIL}
    restart: always
  postgres:
# docker run --name psql-service -p 5432:5432 -d postgres
    image: postgres
    ports:
      - "5432:5432"
