version: '3.4'
services:
#  https:
  java:
    image: maven:3.3.9-jdk-8
    ports:
      - 81:8080
    volumes:
      - ${HOME}/nmr/maven:/root/.m2
      - ${HOME}/glytoucan/java/upload:/upload
      - /etc/localtime:/etc/localtime
      - ./glygen-array-app:/workspace
    working_dir: /workspace/
    command: mvn -U -DskipTests=true spring-boot:run $SPRING_PROFILE
    environment:
      - GOOGLE_OAUTH2_CLIENTID
      - GOOGLE_OAUTH2_CLIENTSECRET
      - SPRING_TRIPLESTORE_PASSWORD
      - SPRING_TRIPLESTORE_URL
    links:
      - virtuoso:internal.virtuoso
      - postgres:internal.postgres
    restart: always
  virtuoso:
    image: aokinobu/virtuoso:v7.2.4.2
    ports:
      - 1111:1111
      - 8890:8890
    volumes:
      - virtuoso-data:/virtuoso
      - /etc/localtime:/etc/localtime
    environment:
      - VIRTUAL_HOST=${VIRTUOSO_VIRTUAL_HOST:-sparql.glygen.org}
      - VIRTUAL_PORT=${VIRTUOSO_VIRTUAL_PORT:-8890}
      - LETSENCRYPT_HOST=${VIRTUOSO_VIRTUAL_HOST:-sparql.glygen.org}
      - LETSENCRYPT_PORT=${VIRTUOSO_VIRTUAL_PORT:-8890}
      - LETSENCRYPT_EMAIL=${SITE_EMAIL:-glygen-array-uga@sparqlite.com}
    restart: always
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rsnapshot:
    build: rsnapshot/
    image: blacklabelops/rsnapshot
    volumes:
      - ${HOME}/${SITE_CODE:-glygen-app}/snapshots/:/snapshots
      - jenkins-data:/var/jenkins_home
      - postgres-data:/var/lib/postgresql/data
      - log:/log/logs
    environment:
      - "BACKUP_DIRECTORIES=/var/jenkins_home/ jenkins_1/; /var/lib/postgresql/data postgres_1/"
      - "RSNAPSHOT_HOURLY_TIMES=4"
      - "RSNAPSHOT_DAILY_TIMES=7"
      - "RSNAPSHOT_WEEKLY_TIMES=4"
      - "RSNAPSHOT_MONTHLY_TIMES=12"
volumes:
  log:
    external:
       name: ${SITE_CODE}-log
    driver: local-persist
    driver_opts:
      mountpoint: $HOME/$SITE_CODE/log/

  jenkins-data:
    external:
       name: ${SITE_CODE}-jenkins
    driver: local-persist
    driver_opts:
      mountpoint: $HOME/$SITE_CODE/jenkins/

  virtuoso-data:
    external:
       name: ${SITE_CODE}-virtuoso
    driver: local-persist
    driver_opts:
      mountpoint: $HOME/$SITE_CODE/virtuoso/

  postgres-data:
    external:
       name: ${SITE_CODE}-postgres
    driver: local-persist
    driver_opts:
      mountpoint: $HOME/$SITE_CODE/postgres/
