server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.glygen.array: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  application:
    name: GlyGen Glycan Array Repository
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 855647983222-r8pf1lvlmkg9at90a3dq3q8gha51qvnu.apps.googleusercontent.com
            client-secret: RKgGxtvpolg70exyi06JjwKC
          github:
            client-id: a22d3d2c1c780f843e27
            client-secret: ff74de601e1a99ae324962e9357068d5c14260c2
