PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX gadr: <http://purl.org/gadr/data#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> INSERT { GRAPH <http://glygen.org/glygenarray/public> { <http://glygen.org/glygenarray/public/SeqA2> gadr:has_sequence_value """RES\n1b:o-dglc-HEX-0:0|1:aldi"""^^xsd:string  .} } WHERE { GRAPH <http://glygen.org/glygenarray/public> { ?glycan rdf:type <http://purl.org/gadr/data#Glycan> . ?glycan rdfs:label "183 Sp8"^^xsd:string . } }