version: '3.4'
services:
  backend:
    image: maven:3.3.9-jdk-8
    ports:
      - 8081:8080
    volumes:
      - ${HOME}/glygen-array/maven:/root/.m2
      - .:/workspace
    working_dir: /workspace/
    command: mvn -U -Djasypt.encryptor.password=${JASYPT_SECRET} -DskipTests=true spring-boot:run
    environment:
      - JASYPT_SECRET
      - GOOGLE_CLIENT_CLIENT-ID
      - GOOGLE_CLIENT_CLIENT-SECRET
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SPRING_TRIPLESTORE_PASSWORD
      - SPRING_TRIPLESTORE_USERNAME
      - SPRING_TRIPLESTORE_URL=${SPRING_TRIPLESTORE_URL:-jdbc:virtuoso://virtuoso:1111}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/glygen}
      - SPRING_DATASOURCE_USERNAME=glygen
      - SPRING_DATASOURCE_PASSWORD
      - GLYGEN_SCHEME=${GLYGEN_SCHEME:-http://}
      - GLYGEN_HOST=${GLYGEN_HOST:-glycomics.ccrc.uga.edu/ggarray}
      - GLYGEN_BASEPATH=${GLYGEN_BASEPATH:-/api}
    restart: always

networks:
  default:
    external:
      name: ${GLYGEN_ARRAY_NETWORK:-glygen-array-network}
