package org.glygen.array.logging.DBappender;

public enum ColumnName {

	EVENT_ID, ACCESS_ID,
	
	TIMESTMP, FORMATTED_MESSAGE, LEVEL_STRING, PARAMETERS, EXCEPTION, CALLER_FILENAME, CALLER_CLASS, CALLER_METHOD, CALLER_LINE, CALLER_USER,
	
	REQUEST_MESSAGE, URI, REQUEST_PAYLOAD, RESPONSE_PAYLOAD,
	
	I, TRACE_LINE;
}
