server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  mail:
    host: pod51004.outlook.com
    port: 587
  triplestore:
    driverClassName: virtuoso.jdbc4.Driver
    dialect: sparql
    url: jdbc:virtuoso://localhost:1111
    username: dba
    password: dba
    graph: graph
google:
    client:
        client-id: 540165369039-5ti43rf0vqhu60o4bo8i9552tvvth570.apps.googleusercontent.com
        client-secret: yTxCpETHfn7ZqXGyAw8M5idF
        accessTokenUri: https://www.googleapis.com/oauth2/v4/token
        userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
        clientAuthenticationScheme: form
        scope: 
          - openid
          - email
          - profile
    resource:
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
        preferTokenInfo: true
glygen:
  scheme: http://
  host: localhost:8080
  basePath: /
