spring:
  profiles:
    active: "dev"
  mail:
    host: pod51004.outlook.com
    port: 587
  datasource:
    url: jdbc:postgresql://localhost:5432/glygen
    username: glygen
    password: ENC(6fDqWRT97iuR7f1U4akTM918JIiZPKRT)
    driver-class-name: org.postgresql.Driver
  triplestore:
    driverClassName: virtuoso.jdbc4.Driver
    dialect: sparql
    url: jdbc:virtuoso://localhost:1111
    username: dba
    password: ENC(6fDqWRT97iuR7f1U4akTM918JIiZPKRT)
    graph: graph
google:
    client:
        client-id: 540165369039-5ti43rf0vqhu60o4bo8i9552tvvth570.apps.googleusercontent.com
        client-secret: ENC(HM+tmiraZ24pKoR97vJnEhuJ7JUpuuMN7p15vgMvX3EHKIdLQScsfA==)
        accessTokenUri: https://www.googleapis.com/oauth2/v4/token
        userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
        clientAuthenticationScheme: form
        scope: 
          - openid
          - email
          - profile
    resource:
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
        tokenInfoUri: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token={accessToken}
        preferTokenInfo: true
        
glygen:
  token-secret: ENC(B/AsM4RnG9dNa6B0lao8sdrlVFKw24VYDfDLgmxSSfcQJupOEdw9iQ==)
  scheme: http://
  host: localhost:8080
  basePath: /
  frontend:
      scheme: http://
      host: localhost:8000
      basePath: /
      loginPage: googleOAuth.html
      emailVerificationPage: emailConfirmation.html
   
server:
  port: 8080
  
---

spring:
  profiles: dev
  datasource:
    initialization-mode: always
  
---

spring:
  profiles: prod
  datasource:
    schema: classpath:/schema-prod.sql
