spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  mail:
    host: pod51004.outlook.com
    port: 587
    protocol: smtps