version: '3.4'
services:
#  https:
  glygen-array-frontend:
    image: maven:3.3.9-jdk-8
    ports:
      - 8081:8080
    volumes:
      - ${HOME}/glygen-array/maven:/root/.m2
      - /etc/localtime:/etc/localtime
      - .:/workspace
    working_dir: /workspace/
    command: mvn -U -DskipTests=true spring-boot:run
    environment:
      - GOOGLE_OAUTH2_CLIENTID
      - GOOGLE_OAUTH2_CLIENTSECRET
      - SPRING_TRIPLESTORE_PASSWORD
      - SPRING_TRIPLESTORE_URL
      - ARRAY_VIRTUAL_HOST
      - ARRAY_VIRTUAL_PORT
    restart: always

networks:
  default:
    external:
      name: ${NETWORK:-glygen-array-network}
