version: '3.4'
services:
  httpd:
    image: httpd:alpine
    ports:
      - 9980:80
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ${HOME}/workspace/glygen-array-frontend/src/:/usr/local/apache2/htdocs/

networks:
  default:
    external:
      name: ${NETWORK:-glygen-array-network}
