version: '3.4'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - $HOME/glygen-array/postgres:/var/lib/postgresql/data

networks:
  default:
    external:
      name: ${GLYGEN_ARRAY_NETWORK:-glygen-array-network}
