version: '3.4'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    external:
       name: ${SITE_CODE}-postgres
    driver: local-persist
    driver_opts:
      mountpoint: $HOME/$SITE_CODE/postgres/
